### ISSUE TITLE
Dream Sexual Pride

### ISSUE THREAD

**Issue by deanOcoin** [angelofallars/prideful#5]
Could you add the Dream Sexual pride flag to the default flags, I would do this myself but I only know Lua and Scratch.
#DreamPride

**Comment by wouu** [comment]
so true

**Comment by angelofallars** [comment]
> Could you add the Dream Sexual pride flag to the default flags, I would do this myself but I only know Lua and Scratch. #DreamPride

SUS 📮📮📮
